# This workflow will build a JavaScript Example
on: push
jobs:
    first-job:
        # runs-on: windows-latest
        runs-on: ubuntu-latest
        container: node:17.6.0-alpine
        steps:
            - run: node --version
            - run: npm --version 

